---
# tasks file for ddclient
#
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install perl ssl package 
  apt: name=libio-socket-ssl-perl state=present
  when: ansible_os_family == "Debian" and ddclient_ssl == "yes" 
  
- name: Install the ddclient packages 
  apt: name={{ item }} state=present
  with_items: ddclient_ubuntu_pkg
  when: ansible_os_family == "Debian"

- name: ddclient | Set ddclient config 
  template: src=ddclient.conf.j2 dest={{ddclient_app_path}}/ddclient.conf
  when: ansible_os_family == "Debian"
  notify: 
    - restart ddclient
